name: "E2E: Testes Cypress"

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências e rodar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Salvar evidências em caso de falha
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: evidencias-falha
          path: |
            cypress/screenshots
            cypress/videos
