name: "E2E: Testes Cypress"

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências e rodar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          browser: chrome
          start: npm run dev # Substitua pelo comando que você usa no terminal local para subir o site (ex: npm start, npm run dev)
          wait-on: "http://localhost:3000" # Aguarda o site responder nesta URL antes de abrir o Cypress
